# library.mk
#
# Date: July 28, 2016
# Author: Brandon Perez
# Author: Jared Choi
#
# The Makefile for building the AXI DMA library.

# Include guard for the Makefile
ifndef LIBAXIDMA_MAKEFILE_
LIBAXIDMA_MAKEFILE_=included

################################################################################
# Configuration
################################################################################

# The flags for compiling the library
LIBAXIDMA_CFLAGS = $(GLOBAL_CFLAGS) -fPIC -shared \
				   -Wno-missing-field-initializers

# The files that makeup the AXI DMA library
LIBAXIDMA_DIR = $(ROOT)/libaxidma
LIBAXIDMA_FILES = libaxidma.c
LIBAXIDMA = $(addprefix $(LIBAXIDMA_DIR)/,$(LIBAXIDMA_FILES))

# The header files for the AXI DMA library interface
LIBAXIDMA_INC_DIRS = $(LIBAXIDMA_DIR)/include
LIBAXIDMA_INC_FILES = libaxidma.h axidma_ioctl.h
LIBAXIDMA_INC = $(addprefix $(LIBAXIDMA_INC_DIRS)/,$(LIBAXIDMA_INC_FILES))
LIBAXIDMA_INC_FLAGS = $(addprefix -I ,$(LIBAXIDMA_INC_DIRS))

# The shared library files generated by compilation
LIBAXIDMA_NAME = libaxidma
LIBAXIDMA_LIBRARY = $(LIBAXIDMA_DIR)/$(LIBAXIDMA_NAME).so
LIBAXIDMA_INSTALL_DIR ?= $(OUTPUT_DIR)

# The Doxygen configuration file and generated libaxidma documentation file
LIBAXIDMA_DOC_CONFIG = libaxidma.dox
LIBAXIDMA_DOC = $(DOC_DIR)/html/index.html

################################################################################
# Targets
################################################################################

.PHONY: libaxidma libaxidma_docs libaxidma_clean

# User-facing targets for compiling the library
libaxidma: $(LIBAXIDMA_LIBRARY)
	install -d $(LIBAXIDMA_INSTALL_DIR)/lib/
	install -m 644 $< $(LIBAXIDMA_INSTALL_DIR)/lib/
	install -d $(LIBAXIDMA_INSTALL_DIR)/include/
	install -m 644 $(LIBAXIDMA_INC) $(LIBAXIDMA_INSTALL_DIR)/include/

# Compile the library into a shared library file
$(LIBAXIDMA_LIBRARY): $(LIBAXIDMA) $(LIBAXIDMA_INC)
	$(CC) $(LIBAXIDMA_CFLAGS) $(LIBAXIDMA_INC_FLAGS) $(filter %.c,$^) -o $@

# Clean up all the files generated by compiling the library
libaxidma-clean:
	rm -f $(LIBAXIDMA_LIBRARY)

endif # LIBAXIDMA_MAKEFILE_
