set_property PACKAGE_PIN M18 [get_ports mosi]
set_property IOSTANDARD LVCMOS33 [get_ports mosi]
set_property PACKAGE_PIN T9 [get_ports miso]
set_property IOSTANDARD LVCMOS33 [get_ports miso]
set_property PACKAGE_PIN U9 [get_ports sclk]
set_property IOSTANDARD LVCMOS33 [get_ports sclk]
set_property PACKAGE_PIN M17 [get_ports ss]
set_property IOSTANDARD LVCMOS33 [get_ports ss]
set_property PACKAGE_PIN U5 [get_ports mclk]
set_property IOSTANDARD LVCMOS33 [get_ports mclk]

set_property PACKAGE_PIN R18 [get_ports bclk]
set_property IOSTANDARD LVCMOS33 [get_ports bclk]
set_property PACKAGE_PIN T17 [get_ports lrclk]
set_property IOSTANDARD LVCMOS33 [get_ports lrclk]
set_property PACKAGE_PIN G18 [get_ports sdata]
set_property IOSTANDARD LVCMOS33 [get_ports sdata]
